/*
 *    DESC: Generated by DFTAdvisor at Fri Nov  9 17:56:18 2018
 */
module mod6_counter_data_flow ( I , Q , CLK , CLR , LC , scan_in1 , scan_en );
input   CLK , CLR , LC , scan_in1 , scan_en ;
input   [2:0] I ;
output  [2:0] Q ;
  wire n34 , n33 , n32 , n31 , n30 , n29 , n17 , d1 , n16 , d2 , n15 , d0 ;

  SDFFR_D  \Q_reg[0]  (.D ( d0 ) , .CLK ( CLK ) , .SI ( scan_in1 ) , .SE 
         ( scan_en ) , .RN ( CLR ) , .Q ( Q[0] ) , .QBAR ( n15 ));
  SDFFR_D  \Q_reg[2]  (.D ( d2 ) , .CLK ( CLK ) , .SI ( Q[1] ) , .SE ( scan_en ) , 
         .RN ( CLR ) , .Q ( Q[2] ) , .QBAR ( n16 ));
  SDFFR_D  \Q_reg[1]  (.D ( d1 ) , .CLK ( CLK ) , .SI ( Q[0] ) , .SE ( scan_en ) , 
         .RN ( CLR ) , .Q ( Q[1] ) , .QBAR ( n17 ));
  OAI21_A  U25 (.A1 ( n16 ) , .A2 ( n29 ) , .B ( n30 ) , .Z ( d2 ));
  MUX21I_B  U26 (.D0 ( n31 ) , .D1 ( I[2] ) , .SD ( LC ) , .Z ( n30 ));
  NOR2_A  U27 (.A ( n17 ) , .B ( n15 ) , .Z ( n31 ));
  OAI21_A  U28 (.A1 ( n17 ) , .A2 ( n29 ) , .B ( n32 ) , .Z ( d1 ));
  MUX21I_B  U29 (.D0 ( n33 ) , .D1 ( I[1] ) , .SD ( LC ) , .Z ( n32 ));
  AND3_B  U30 (.A ( n16 ) , .B ( Q[0] ) , .C ( n17 ) , .Z ( n33 ));
  INVERT_A  U31 (.A ( n34 ) , .Z ( n29 ));
  AO21_B  U32 (.A1 ( I[0] ) , .A2 ( LC ) , .B ( n34 ) , .Z ( d0 ));
  NOR2_A  U33 (.A ( Q[0] ) , .B ( LC ) , .Z ( n34 ));
endmodule

